name: Create and publish a Docker image

on:
  push:
    branches: ['release']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2    
      # First we need to build the app
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x website/gradlew
      - name: Build with Gradle
        run: cd website; ./gradlew bootBuildImage --imageName=ghcr.io/tytanrock/home-status
      # Now do package deployment stuff
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the docker image
        run: |
          name="$(echo '${{ github.actor }}' | awk '{print tolower($0)}')"
          docker push "ghcr.io/$name/home-status"
